### ISSUE TITLE
alexa-skills-kit-nodejs-factskill Lambda function not deploying.

### ISSUE THREAD

**Issue by juliaguida** [yolossn/Prometheus-Basics#14]
Hi team, when I click on deploy the Alexa_skills, Lambda throws the following error message:

**### Change set creation failed. Reason: No updates are to be performed.**

Thank you.

**Comment by yolossn** [comment]
By chance, did you raise the issue in the wrong repository?

**Comment by yolossn** [comment]
Closing the issue as it looks irrelevant and no reply, please feel free to reopen if you think otherwise.
